#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: İbrahim ATAY

# Name of the author
author: İbrahim ATAY

# Short bio or description (displayed in the header)
description: As an experienced architect and leader, he helps organizations achieve their business goals and stay ahead of the competition in the ever-changing tech world.
headline: Senior Software Architect

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars.githubusercontent.com/u/172555?v=4

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: 
  facebook:
  flickr:
  github: ibrahimatay
  instagram: agilestorytelling
  linkedin: ibrahimatay
  pinterest:
  rss: 
  twitter: ibrahim_atay
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:
  scrumallice: ibrahimatay
  kanbanuniversity: ibrahimatay
  goodreads: 


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-105833516-1

# For newer "GA4" analytics, use the following instead of the "UA" entry above
#google_analytics_ga4: G-GABC1DEFG

# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
# url: http://www.ibrahimatay.com/
url:  # development
enforce_ssl: https://www.ibrahimatay.com/ # production

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: # development
# baseurl: "/" # production

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: posts/:year/:month/:day/:title
#permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

markdown: kramdown

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 6
paginate_path: "blog/page:num/"

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

future: true


# commands
# - bundle install
# - jekyll build
# - jekyll serve
# - jekyll serve --drafts

# template
#---
#layout: post
#title: Introducing Reverie - A ridiculously elegant Jekyll theme
#categories: [Miscellaneous, Jekyll]
#paginate: true
#---
